"""Data models used by the generator service."""

from .consultation import (
    AiSoapNoteError,
    AiSoapNoteStatus,
    BillingStatus,
    ConsultationBillingCodeRecord,
    ConsultationCallRequestRecord,
    ConsultationCallRequestState,
    ConsultationRecord,
    ConsultationType,
    SuggestedConfidence,
)
from .patient import Gender, PatientRecord, PatientSeed, PatientStatus
from .patient_related import (
    AllergyCategory,
    AllergyClinicalStatus,
    AllergySeverity,
    AllergyType,
    ConditionClinicalStatus,
    EhrConnectionStatus,
    MedicationStatus,
    PatientAllergyRecord,
    PatientConditionRecord,
    PatientCoverageRecord,
    PatientMedicationRecord,
    PatientObservationRecord,
    PayerType,
)

__all__ = [
    "AiSoapNoteError",
    "AiSoapNoteStatus",
    "AllergyCategory",
    "AllergyClinicalStatus",
    "AllergySeverity",
    "AllergyType",
    "BillingStatus",
    "ConsultationBillingCodeRecord",
    "ConsultationCallRequestRecord",
    "ConsultationCallRequestState",
    "ConsultationRecord",
    "ConsultationType",
    "ConditionClinicalStatus",
    "EhrConnectionStatus",
    "Gender",
    "MedicationStatus",
    "PatientRecord",
    "PatientAllergyRecord",
    "PatientConditionRecord",
    "PatientCoverageRecord",
    "PatientMedicationRecord",
    "PatientObservationRecord",
    "PatientSeed",
    "PatientStatus",
    "PayerType",
    "SuggestedConfidence",
]
